### ISSUE TITLE
Module not found: Error: Cannot resolve module 'es6-object-assign'

### ISSUE THREAD

**Issue by Peramanathan** [stanleycyang/react-bible-boilerplate#3]
```
ERROR in ./client/polyfills.js
Module not found: Error: Cannot resolve module 'es6-object-assign' in /../react-bible-boilerplate/examples/book-inventory/client
 @ ./client/polyfills.js 12:0-28
```

**Comment by Peramanathan** [comment]
`npm install es6-object-assign --dev` actually fixed ! Just to help other newbies and for the completeness I opened this issue

**Comment by stanleycyang** [comment]
Thanks! It looks like the package.json had it included before: `https://github.com/stanleycyang/react-bible-boilerplate/blob/master/package.json#L7`. How were you installing your initial dependencies?

**Comment by peramsathyam** [comment]
Oh damn ! I forgot to mention that I was running your examples directly before running this boilerplate
`https://github.com/stanleycyang/react-bible-boilerplate/blob/master/examples/book-inventory/package.json` which obviously not having it

**Comment by stanleycyang** [comment]
Haha I see
