### ISSUE TITLE
How to add css to boilerplate?

### ISSUE THREAD

**Issue by crapthings** [stanleycyang/react-bible-boilerplate#5]
css with hmr

**Comment by stanleycyang** [comment]
I recommend using [webpack-isomorphic-tools](https://www.npmjs.com/package/webpack-isomorphic-tools) to handle dealing with CSS. There is a really good boilerplate provided with the project as well that walks you through how to use **CSS / LESS / SASS**

**Comment by crapthings** [comment]
thanks yang~

i'm reading your react and redux tutorial, it's really great.

**Comment by stanleycyang** [comment]
You're welcome! And thank you, that means a lot
